# Generated by Django 4.2.30 on 2026-08-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SEVEN_DAY', '7 days before start'), ('ONE_DAY', '1 day before start')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='orders.order')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('order', 'kind')},
            },
        ),
    ]
