# Generated by Django 4.2.30 on 2026-08-13 18:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def backfill_subtotal(apps, schema_editor):
    """Existing orders predate coupons, so they were never discounted:
    their subtotal is exactly what was charged. Without this they would all
    report a ₹0 package price."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.update(subtotal_amount=models.F('total_amount'))


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0003_orderreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(backfill_subtotal, migrations.RunPython.noop),
    ]
