# Generated by Django 4.2.29 on 2026-09-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_coupon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_buyer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_buyer', 'id'],
                'unique_together': {('order', 'user')},
            },
        ),
        migrations.AddField(
            model_name='orderreminder',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='orders.orderparticipant'),
        ),
    ]
