# Generated by Django 4.2.30 on 2026-06-26 19:36

from django.db import migrations, models


def copy_location_to_locations(apps, schema_editor):
    """Preserve existing data: copy each package's single `location` FK into the new M2M."""
    Package = apps.get_model('packages', 'Package')
    for package in Package.objects.exclude(location__isnull=True).iterator():
        package.locations.add(package.location_id)


def copy_locations_to_location(apps, schema_editor):
    """Reverse: put the first M2M location back into the `location` FK."""
    Package = apps.get_model('packages', 'Package')
    for package in Package.objects.iterator():
        first = package.locations.first()
        if first is not None:
            package.location_id = first.id
            package.save(update_fields=['location'])


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('packages', '0003_package_start_date_package_type_and_more'),
    ]

    operations = [
        # 1. Add the new fields (M2M + content sections + kind) BEFORE removing `location`.
        migrations.AddField(
            model_name='package',
            name='accommodation',
            field=models.JSONField(blank=True, default=list, help_text="List of bullet points for 'Accommodation'"),
        ),
        migrations.AddField(
            model_name='package',
            name='experience',
            field=models.JSONField(blank=True, default=list, help_text="List of bullet points for 'Experience'"),
        ),
        migrations.AddField(
            model_name='package',
            name='ideal_for',
            field=models.JSONField(blank=True, default=list, help_text="List of bullet points for 'Ideal For'"),
        ),
        migrations.AddField(
            model_name='package',
            name='included',
            field=models.JSONField(blank=True, default=list, help_text="List of bullet points for 'Included'"),
        ),
        migrations.AddField(
            model_name='package',
            name='kind',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='packages', to='locations.location'),
        ),
        migrations.AddField(
            model_name='package',
            name='training',
            field=models.JSONField(blank=True, default=list, help_text="List of bullet points for 'Training'"),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Total program duration in days', null=True),
        ),
        # 2. Migrate existing location data from the FK into the M2M.
        migrations.RunPython(copy_location_to_locations, copy_locations_to_location),
        # 3. Now it's safe to drop the old single-location FK.
        migrations.RemoveField(
            model_name='package',
            name='location',
        ),
    ]
