# Generated by Django 4.2.29 on 2026-08-30 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_locationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo, The Democratic Republic of the'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('CI', "Côte d'Ivoire"), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See (Vatican City State)'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia, Federated States of'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('KP', 'North Korea'), ('MK', 'North Macedonia'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestine, State of'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('RE', 'Réunion'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('KR', 'South Korea'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('TR', 'Türkiye'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('US', 'United States'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('VG', 'Virgin Islands, British'), ('VI', 'Virgin Islands, U.S.'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('AX', 'Åland Islands')], max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('training_duration', models.CharField(blank=True, choices=[('NEVER', 'Never / Brand new'), ('UNDER_3_MONTHS', 'Less than 3 months'), ('THREE_TO_SIX_MONTHS', '3–6 months'), ('SIX_TO_TWELVE_MONTHS', '6–12 months'), ('ONE_TO_TWO_YEARS', '1–2 years'), ('TWO_TO_FIVE_YEARS', '2–5 years'), ('FIVE_PLUS_YEARS', '5+ years')], max_length=32)),
                ('training_frequency', models.CharField(blank=True, choices=[('NOT_TRAINING', 'Not currently training'), ('ONE_DAY', '1 day'), ('TWO_DAYS', '2 days'), ('THREE_DAYS', '3 days'), ('FOUR_DAYS', '4 days'), ('FIVE_DAYS', '5 days'), ('SIX_PLUS_DAYS', '6+ days')], max_length=32)),
                ('trained_in_thailand', models.BooleanField(blank=True, null=True)),
                ('thailand_trips', models.CharField(blank=True, choices=[('ONCE', 'Once'), ('TWO_TO_THREE', '2–3 times'), ('FOUR_PLUS', '4+ times')], max_length=32)),
                ('other_combat_sports', models.JSONField(blank=True, default=list)),
                ('competition_experience', models.CharField(blank=True, choices=[('NEVER', 'Never'), ('MUAY_THAI', 'Yes — Muay Thai'), ('BOXING', 'Yes — Boxing'), ('KICKBOXING', 'Yes — Kickboxing'), ('MMA', 'Yes — MMA'), ('OTHER', 'Yes — Other combat sport')], max_length=32)),
                ('fight_count', models.CharField(blank=True, choices=[('ONE', '1'), ('TWO_TO_FIVE', '2–5'), ('SIX_TO_TEN', '6–10'), ('TEN_PLUS', '10+')], max_length=32)),
                ('sparring_experience', models.CharField(blank=True, choices=[('NEVER', 'Never'), ('A_FEW_TIMES', 'A few times'), ('OCCASIONALLY', 'Occasionally'), ('REGULARLY', 'Regularly'), ('FREQUENTLY', 'Frequently')], max_length=32)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('NONE', "I don't currently exercise"), ('ONE_DAY', '1 day'), ('TWO_DAYS', '2 days'), ('THREE_DAYS', '3 days'), ('FOUR_DAYS', '4 days'), ('FIVE_DAYS', '5 days'), ('SIX_DAYS', '6 days'), ('EVERY_DAY', 'Every day')], max_length=32)),
                ('cardio_level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner — I get tired quickly'), ('BELOW_AVERAGE', 'Below average — I can exercise, but cardio is challenging'), ('AVERAGE', 'Average — I can handle moderate training'), ('GOOD', 'Good — I can train for long periods without struggling'), ('EXCELLENT', 'Excellent — I have strong endurance and recover quickly')], max_length=32)),
                ('five_round_capability', models.CharField(blank=True, choices=[('YES_COMFORTABLY', 'Yes, comfortably'), ('YES_BUT_TIRED', 'Yes, but I would be tired'), ('MAYBE', 'Maybe / Not sure'), ('PROBABLY_NOT', 'Probably not'), ('NO', 'No')], max_length=32)),
                ('overall_fitness', models.PositiveSmallIntegerField(blank=True, help_text='1–10, where 1 is very low fitness and 10 is excellent fitness.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('goals', models.JSONField(blank=True, default=list, help_text='Up to 3 goals.')),
                ('primary_focus', models.CharField(blank=True, choices=[('TECHNIQUE', 'Technique'), ('STRIKING', 'Striking'), ('DEFENCE', 'Defence'), ('FOOTWORK', 'Footwork'), ('CLINCH', 'Clinch'), ('CARDIO', 'Cardio'), ('ENDURANCE', 'Endurance'), ('STRENGTH', 'Strength'), ('SPARRING', 'Sparring'), ('CONFIDENCE', 'Confidence'), ('FIGHT_READINESS', 'Fight readiness'), ('OTHER', 'Other')], max_length=32)),
                ('primary_focus_notes', models.TextField(blank=True)),
                ('fighting_styles', models.JSONField(blank=True, default=list, help_text='Up to 2 styles.')),
                ('favourite_techniques', models.JSONField(blank=True, default=list, help_text='Up to 2 techniques.')),
                ('injury_status', models.CharField(blank=True, choices=[('NO', 'No'), ('YES_MINOR', 'Yes — Minor'), ('YES_MODERATE', 'Yes — Moderate'), ('YES_SIGNIFICANT', 'Yes — Significant'), ('PREFER_TO_DISCUSS', 'Prefer to discuss with trainer')], max_length=32)),
                ('injury_areas', models.JSONField(blank=True, default=list)),
                ('injury_notes', models.TextField(blank=True)),
                ('has_past_major_injury', models.BooleanField(blank=True, null=True)),
                ('past_injury_types', models.JSONField(blank=True, default=list)),
                ('training_restrictions', models.JSONField(blank=True, default=list)),
                ('training_restrictions_notes', models.TextField(blank=True)),
                ('has_medical_condition', models.BooleanField(blank=True, null=True)),
                ('medical_details', models.TextField(blank=True)),
                ('coach_intensity', models.PositiveSmallIntegerField(blank=True, help_text='1–10, where 1 is keep it light and 10 is push me to my limit.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('train_around_limitations', models.BooleanField(default=False)),
                ('message_to_kru', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fighter_cards', to='locations.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fighter_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fighter card',
                'verbose_name_plural': 'fighter cards',
                'db_table': 'fighters_fightercard',
                'ordering': ['-updated_at'],
            },
        ),
    ]
