# Generated by Django 4.2.30 on 2026-08-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightercard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fighter-cards/'),
        ),
    ]
