# Generated by Django 4.2.30 on 2026-06-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience_level',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='height_cm',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='passport_number',
            new_name='passport',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
