# Generated by Django 4.2.29 on 2026-09-01 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_experience_level_profile_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sections', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profile_share',
                'ordering': ['-created_at'],
            },
        ),
    ]
